name: Swift

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Test
        run: swift test

  linux:
    runs-on: ubuntu-latest
    container: swift:5.10
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
